backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "src/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "recommendations" # Used in routes, e.g., /admin/collections/blog
    label: "Recommendation" # Used in the UI
    folder: "src/recommendations" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "recommendation.njk",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Publish Date",
          name: "date",
          widget: "string",
          hint: "Must be in the format: YYYY-MM-DD. For example: 2020-09-18",
        }
      - { label: "Book Cover", name: "book_cover", widget: "image" }
      - {
          label: "Recommendation Content",
          name: "recommendation_content",
          widget: "markdown",
        }
      - {
          label: "Recommendation Genre",
          name: "recommendation_genre",
          widget: "string",
        }
      - {
          label: "Recommendation Reading Level",
          name: "recommendation_reading_level",
          widget: "string",
        }
      - {
          label: "Recommendation Publication Info",
          name: "recommendation_publication_info",
          widget: "string",
        }
      - {
          label: "Tags",
          name: "tags",
          widget: "hidden",
          default: "recommendation",
        }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Sitewide Data"
        name: "Sitewide"
        file: "src/_data/site.json"
        fields:
          - { label: Page One, name: Page1_Title, widget: string }
          - { label: Page Two, name: Page2_Title, widget: string }
          - { label: Page Three, name: Page3_Title, widget: string }
          - { label: Page Four, name: Page4_Title, widget: string }
          - { label: Page Five, name: Page5_Title, widget: string }
          - { label: Logo, name: Logo, widget: image }
          - { label: Logo - Black and White, name: LogoBW, widget: image }
      - label: "Homepage"
        name: "Homepage"
        file: "src/_data/homepage.json"
        fields:
          - { label: Homepage Banner, name: homepage_banner, widget: image }
          - { label: Homepage Subheading, name: subheading, widget: string }
      - label: "My Books"
        name: "MyBooks"
        file: "src/_data/myBooks.json"
        fields:
          - { label: My Books Banner, name: myBooks_banner, widget: image }
          - { label: My Books Subheading, name: myBooks_subheading, widget: string }
          - { label: My Books Content Top, name: myBooks_content_top, widget: markdown }
          - { label: My Books Content MMD, name: myBooks_content_mmd, widget: markdown }
          - { label: My Books Content WIP, name: myBooks_content_wip, widget: markdown }
      - label: "Kidlit Resources"
        name: "MyBooks"
        file: "src/_data/kidlitResources.json"
        fields:
          - { label: Kidlit Resources Banner, name: kidlitResources_banner, widget: image }
          - { label: Kidlit Resources Subheading, name: kidlitResources_subheading, widget: string }
          - { label: Kidlit Resources Content Top, name: kidlitResources_content_top, widget: markdown }
       
          

 